repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: clippy
    -   id: cargo-check
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
    -   id: clang-format
