repos:
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
  - id: clippy
  - id: cargo-check
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v13.0.1
  hooks:
  - id: clang-format
    types: [file]
- repo: https://github.com/nametake/pre-commit-buf
  rev: v2.0.0
  hooks:
  - id: buf-lint
