name: Misc

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  license:
    name: Check license headers
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check License Header
      uses: enarx/spdx@master
      with:
        licenses: Apache-2.0 MIT

  editorconfig:
    name: Check editorconfig
    runs-on: ubuntu-latest
    steps:
      - uses: editorconfig-checker/action-editorconfig-checker@v1
