name: PR Build Check

on:
  pull_request:
jobs:
  editorconfig-checker:
    name: Check editorconfig
    runs-on: ubuntu-latest
    steps:
      - uses: editorconfig-checker/action-editorconfig-checker@v1
  proto-format-check:
    name: Check Protobuf Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: bufbuild/buf-setup-action@v1.3.1
      - run: buf format --diff --exit-code
  proto:
    name: Check Protobuf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: arduino/setup-protoc@v1
      - uses: bufbuild/buf-setup-action@v0.7.0
      - uses: bufbuild/buf-lint-action@v1
      - name: Compile protobuf
        run: buf generate
  yamllint:
    name: Lint YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run yamllint
        run: yamllint .
